plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\anti\\20260501001\\GitHub_Pages_教學駕駛艙"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]